# Generated by Django 4.0 on 2022-01-11 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('text_context', models.TextField(verbose_name='text context')),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts_images/', verbose_name='image')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                            related_name='posts',
                                            to='auth.user',
                                            verbose_name='owner'
                                            )
                 ),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-creation_date'],
            },
        ),
    ]
