<<<<<<< HEAD
# Generated by Django 4.0 on 2022-02-25 17:01
=======
# Generated by Django 4.0 on 2022-02-19 21:59
>>>>>>> 792b6c700bd4aa107a64929b931d414dff190757

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_edited'),
        ('posts', '0002_post_hidden'),
    ]

<<<<<<< HEAD
    operations = [
=======
    operations: list = [
>>>>>>> 792b6c700bd4aa107a64929b931d414dff190757
    ]
